openapi: "3.0.1"
info:
  version: 0.0.1
  title: Woodnet
  description: Woodnet Backend API
paths:
  /test:
    get:
      operationId: getTest
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: GET
        uri: "${test_arn}"
        payloadFormatVersion: "2.0"
        connectionType: INTERNET