openapi: "3.0.1"
info:
  version: 0.0.1
  title: Woodnet
  description: Woodnet Backend API
paths:
  /create-user:
    post:
      produces:
      - application/json
      operationId: createUser
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${create_user_lambda_invoke_arn}
        type: aws_proxy
  /reset-password:
    post:
      produces:
      - application/json
      operationId: createUser
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${reset_password_lambda_invoke_arn}
        type: aws_proxy
  /sign-in:
    post:
      produces:
      - application/json
      operationId: createUser
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${sign_in_lambda_invoke_arn}
        type: aws_proxy
  /start-ark:
    post:
      produces:
      - application/json
      operationId: startArk
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${start_ark_lambda_invoke_arn}
        type: aws_proxy
  /stop-ark:
    post:
      produces:
      - application/json
      operationId: stopArk
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${stop_ark_lambda_invoke_arn}
        type: aws_proxy
  /test:
    get:
      produces:
      - application/json
      operationId: getTest
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${test_lambda_invoke_arn}
        type: aws_proxy