openapi: "3.0.1"
info:
  version: 0.0.1
  title: Woodnet
  description: Woodnet Backend API
paths:
  /test:
    get:
      produces:
      - application/json
      operationId: getTest
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${test_lambda_invoke_arn}
        type: aws_proxy
  /start-ark:
    put:
      produces:
      - application/json
      operationId: startArk
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${start_ark_lambda_invoke_arn}
        type: aws_proxy
  /stop-ark:
    put:
      produces:
      - application/json
      operationId: stopArk
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: ${stop_ark_lambda_invoke_arn}
        type: aws_proxy