openapi: "3.0.1"
info:
  version: 0.0.1
  title: Woodnet
  description: Woodnet Backend API
paths:
  /test:
    get:
      produces:
      - application/json
      operationId: getTest
      responses:
        '200':
          description: 200 response
          schema:
            "$ref": "#/definitions/Result"
          headers:
            operand_1:
              type: string
            operand_2:
              type: string
            operator:
              type: string
      x-amazon-apigateway-integration:
        httpMethod: GET
        uri: ${lambda_invoke_arn}
        type: aws
definitions:
  Input:
    type: object
    required:
    - a
    - b
    - op
    properties:
      a:
        type: number
      b:
        type: number
      op:
        type: string
        description: binary op of ['+', 'add', '-', 'sub', '*', 'mul', '%2F', 'div']
    title: Input
  Output:
    type: object
    properties:
      c:
        type: number
    title: Output
  Result:
    type: object
    properties:
      input:
        "$ref": "#/definitions/Input"
      output:
        "$ref": "#/definitions/Output"
    title: Result