name: Gigaplat host
on: 
  repository_dispatch:
    types: [s3-frontend]
  # push:
  #   branches: [ "main", "dev" ]
  # pull_request:
  #   branches: [ "main", "dev" ]

env:
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
  REACT_PATH: modules/frontend/src/
  CI: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: Brennan-Flood/Rust_Platformer
        token: ${{ secrets.PLATFORMER_PAT }
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.70.0
        override: true
        components: rustfmt, clippy
    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: libasound2-dev libudev-dev
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/            
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Check
      run: |
        cargo check
    - name: Lint
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -D warnings 
    - run: aws s3 cp index.html s3://${{ env.ENVIRONMENT }}-gigaplat
